config/routes.rb
Rails.application.routes.draw do

  root 'media_contents#index'

  resources :media_contents, only: [:create]

  delete 'delete_media', to: "media_contents#delete_media"
  delete 'delete_all', to: 'media_contents#delete_all'

end

app/models/media.rb
class Media < ActiveRecord::Base
  mount_uploader :file_name, MediaUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/media_contents_controller.rb
class MediaContentsController < ApplicationController

  def index
    @media_contents = Media.all
  end

 def create
    @media = Media.new(file_name: params[:file])
    if @media.save!
      render json: @media
    else
      puts 'Hello'
      render json: { error: 'Failed to process' }, status: 422
    end
  end

def delete_media
  Media.where(id: params[:media_contents]).destroy_all
  redirect_to root_url
end

def delete_all
  Media.delete_all
  redirect_to root_url
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_contents_helper.rb
module MediaContentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dropzone Rails demo</title>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/media_contents/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><b>Dropzone Sample</b></a>
  </div>
</nav>
<div class="container">
  <div class="row" style="margin-top: 50px;">
    <div class="col-lg-4 col-lg-offset-1">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Upload New</button>
    </div>
  </div>
  <div class="row" style="margin-top: 25px;">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="well">
        <h4><b>Media</b></h4><hr>
        <div class="row">
          <div class="col-lg-10">
            <%= form_tag '/delete_media', method: :delete do %>
              <%= submit_tag 'Delete', id: 'delete', class: 'btn btn-danger', disabled: @media_contents.empty? %>
              <br><br>
              <div class="row">
                <div id="media-contents" class="col-lg-12">
                  <% if @media_contents.empty? %>
                    <h5 id="no-media">No Media Found</h5>
                  <% else %>
                    <% @media_contents.each do |media| %>
                      <div class="col-lg-4">
                        <div class="thumbnail">
                          <%= image_tag media.file_name.url %>
                          <div class="caption">
                            <p>
                              <%= check_box_tag 'media_contents[]', media.id %>
                            </p>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="col-lg-1">
            <%= link_to 'Delete All', delete_all_path, method: :delete, id: 'delete-all', class: 'btn btn-danger', disabled: @media_contents.empty? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Upload New</h4>
      </div>
      <div class="modal-body">
        <%= form_tag '/media_contents', method: :post, class: 'dropzone form', id: 'media-dropzone' do %>
          <div class="fallback">
            <%= file_field_tag 'media', multiple: true %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>